In [1]:
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
import numpy as np
import pandas as pd
plt.ion()

In [2]:
df="https://archive.ics.uci.edu/ml/machine-learning-databases/00451/dataR2.csv"
df=pd.read_csv(df)

In [3]:
df.head()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,48,23.500000,70,2.707,0.467409,8.8071,9.702400,7.99585,417.114,1
1,83,20.690495,92,3.115,0.706897,8.8438,5.429285,4.06405,468.786,1
2,82,23.124670,91,4.498,1.009651,17.9393,22.432040,9.27715,554.697,1
3,68,21.367521,77,3.226,0.612725,9.8827,7.169560,12.76600,928.220,1
4,86,21.111111,92,3.549,0.805386,6.6994,4.819240,10.57635,773.920,1

In [4]:
#periksa jumlah baris dan kolom dalam dataset
df.shape

(116, 10)

In [5]:
#Pilih data menjadi variabel independen 'X' dan variabel 'Y'
X = df.iloc[:, 0:9].values 
Y = df.iloc[:,9].values
#ATAU
#X=df.drop("Klasifikasi", sumbu=1)
#Y=df["Klasifikasi"]

In [6]:
## Jika ada yang melihat data dengan fitur (X)
all_columns=['Age', 'BMI', 'Glucose', 'Insulin', 'HOMA', 'Leptin', 'Adiponectin','Resistin', 'MCP.1']

X = pd.DataFrame(X,columns=all_columns[0:9])
all_columns[0:9]
X.head()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1
0,48.0,23.500000,70.0,2.707,0.467409,8.8071,9.702400,7.99585,417.114
1,83.0,20.690495,92.0,3.115,0.706897,8.8438,5.429285,4.06405,468.786
2,82.0,23.124670,91.0,4.498,1.009651,17.9393,22.432040,9.27715,554.697
3,68.0,21.367521,77.0,3.226,0.612725,9.8827,7.169560,12.76600,928.220
4,86.0,21.111111,92.0,3.549,0.805386,6.6994,4.819240,10.57635,773.920

In [7]:
Y[:]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [8]:
#Pisahkan dataset menjadi 80% set Pelatihan dan 20% set Pengujian
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)

In [9]:
#Penskalaan Fitur
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train[:5]

array([[-0.90580006, -0.60223851,  0.39996142,  5.41266386,  3.97788424,
        -0.48294549,  1.01615946, -0.73302693, -0.83359765],
       [-1.1590937 , -0.01445999,  0.26128133, -0.79254154, -0.59226514,
        -0.67908362, -0.50242597,  0.88574816, -0.67899565],
       [-0.84247665, -0.17399633, -0.24721234, -0.69308636, -0.54932947,
         1.38357642,  0.36413531, -0.29126418, -0.75855465],
       [ 0.9939022 ,  0.19135671, -0.43211912, -0.72830546, -0.58107469,
         0.17960335, -0.36087967,  0.28699465,  0.21358775],
       [ 0.93057879, -1.15834447, -0.01607885, -0.69087133, -0.53504167,
        -1.18263566,  0.08029698, -0.65683654, -1.17843428]])

In [10]:
def models(X_train,Y_train):
  
  #Menggunakan Metode KNeighborsClassifier dari kelas tetangga untuk menggunakan algoritma Nearest Neighbor
  from sklearn.neighbors import KNeighborsClassifier
  knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
  knn.fit(X_train, Y_train)

    
  #mencetak akurasi model pada data pelatihan.
  print(knn.score(X_train, Y_train))
  return knn

model = models(X_train,Y_train)

0.8260869565217391